services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/resume_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resume_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username" ]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 10s
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
